export const types = {
  LOGIN: "LOGIN_USER",
  NOTICE_MSG_REGISTER: "NOTICE_MSG_REGISTER",
  NOTICE_MSG_lOGIN: "NOTICE_MSG_LOGIN",
  LOGOUT: "LOGOUT_USER",
  GET_COUNTRIES: "GET_COUNTRIES",
  ADD_COUNTRY: "ADD_COUNTRY",
  CLEAN_DATA: "CLEAN_DATA",
  DELETE_COUNTRY: "DELETE_COUNTRY",
};
